### ISSUE TITLE
Error when i sell something

### ISSUE THREAD

**Issue by Legired** [CCMG-Minecraft/QuickSellReloaded#1]
## Description (Required)
When i try sell item with /sellall a, i have an error

## Steps to reproduce the Issue (Required)
![2020-11-05_11 28 02](https://user-images.githubusercontent.com/33747013/98229450-37e1e180-1f5a-11eb-9f33-962e05c75cec.png)

## Server Log / Error Report
http://pastebin.fr/71228

## Environment (Required)
Minecraft Spigot V1.16.3

 - Minecraft Version: 1.16.3
 - QuickSell Version: 3.1.0

**Comment by PhilCCMG** [comment]
Have a look at this section of the config.yml
```yml
sound:
  enabled: true
  sound: ORB_PICKUP
```

The `sound` you provided doesn't exist on 1.16

A full list is available at https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html, or to fix in your case, change `ORB_PICKUP` to `ENTITY_EXPERIENCE_ORB_PICKUP`.
