### ISSUE TITLE
Plugin not loading

### ISSUE THREAD

**Issue by KieranHowland** [CCMG-Minecraft/QuickSellReloaded#2]
## Description (Required)
Plugin not loading, not sure what causes it 

## Steps to reproduce the Issue (Required)
Just load the plugin

## Expected behavior (Required)
The plugin will load

## Server Log / Error Report
https://pastebin.com/2KsnXTJv

## Environment (Required)
Paper 1.16.4 (git-Paper-407) (API 1.16.4-R0.1-SNAPSHOT)

 - Minecraft Version: 1.16.4
 - QuickSell Version: 3.1.0

**Comment by PhilCCMG** [comment]
Hi there! Can you send a copy of your `config.yml` file?
Your Error Report indicates that you have a badly formatted item name somewhere.

**Comment by PhilCCMG** [comment]
From doing a bit more digging, I believe this was fixed by https://github.com/ccmg-minecraft/quicksellreloaded/commit/ae396637

I'll build the code tomorrow and upload it as a release.

**Comment by KieranHowland** [comment]
Alrighty thanks 👍

**Comment by PhilCCMG** [comment]
Hi there.

This should be fixed in 3.1.2 - https://github.com/CCMG-Minecraft/QuickSellReloaded/releases/tag/3.1.2

Thanks!
